CONFIG_HEAP_MEM_POOL_SIZE=1048
CONFIG_ASSERT=y
CONFIG_GPIO=y
CONFIG_ADC=y

CONFIG_SHELL=y
#CONFIG_ADC_SHELL=y
#CONFIG_GPIO_SHELL=y
CONFIG_SHELL_PROMPT_UART="chessboard:~$ "

CONFIG_REBOOT=y

CONFIG_LOG=y

CONFIG_EVENTS=y

CONFIG_MAIN_STACK_SIZE=2048

CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_CRC=y


CONFIG_BOOTLOADER_MCUBOOT=y
#CONFIG_BOOT_SIGNATURE_KEY_FILE="~/keys/mykey.pem"
#CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="/home/elotro/keys/mykey.pem"

#CONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE
CONFIG_MCUBOOT_IMGTOOL_SIGN_VERSION="0.0.1"


CONFIG_NET_BUF=y
CONFIG_ZCBOR=y

# Enable mcumgr.
CONFIG_MCUMGR=y

CONFIG_MCUBOOT_BOOTLOADER_MODE_FIRMWARE_UPDATER=y

# Enable the Bluetooth (unauthenticated) and UART mcumgr transports.
#CONFIG_MCUMGR_SMP_BT=y
#CONFIG_MCUMGR_SMP_BT_AUTHEN=n
#CONFIG_MCUMGR_SMP_SHELL=y
#CONFIG_MCUMGR_SMP_UART=y

# Enable all core commands.
#CONFIG_MCUMGR_CMD_FS_MGMT=y
#CONFIG_MCUMGR_CMD_IMG_MGMT=y
#CONFIG_MCUMGR_CMD_OS_MGMT=y
#CONFIG_MCUMGR_CMD_STAT_MGMT=y

#CONFIG_BASE64=y
#CONFIG_MCUMGR_TRANSPORT_UART=y


#CONFIG_IMG_MANAGER=y
#CONFIG_STREAM_FLASH=y
#CONFIG_RETENTION_BOOTLOADER_INFO_OUTPUT_FUNCTION=y
#CONFIG_RETENTION=y
#CONFIG_RETAINED_MEM=y

#CONFIG_MCUBOOT_BOOTUTIL_LIB=y
#CONFIG_BOOT_IMAGE_ACCESS_HOOKS=y # probando..


#CONFIG_MCUMGR_GRP_IMG=y
#CONFIG_MCUMGR_SMP_VERBOSE_ERR_RESPONSE=y



#CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="/home/elotro/keys/mykey.pem"
CONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE=y


