CONFIG_BOOT_FIRMWARE_LOADER=y
CONFIG_BOOT_FIRMWARE_LOADER_NO_APPLICATION=y

#SW Reset also enables pin reset.... undesired entering to upgrader
#CONFIG_BOOT_FIRMWARE_LOADER_PIN_RESET=y


CONFIG_BOOT_SIGNATURE_KEY_FILE="/home/elotro/keys/mykey.pem"


CONFIG_MCUBOOT_LOG_LEVEL_DBG=y
CONFIG_HWINFO_LOG_LEVEL_DBG=y

