<CalculatorUI>:
    orientation: "vertical"
    padding: 20
    spacing: 10

    TextInput:
        id: input_a
        hint_text: "Enter A"
        input_filter: "float"

    TextInput:
        id: input_b
        hint_text: "Enter B"
        input_filter: "float"

    BoxLayout:
        spacing: 10
        size_hint_y: None
        height: "40dp"

        Button:
            text: "Start (Sync)"
            on_press: root.on_start_sync()

        Button:
            text: "Start (Async)"
            on_press: root.on_start_async()

    ProgressBar:
        max: 100
        value: root.progress

    Label:
        text: "Status: " + root.status
    Label:
        text: "Result: " + root.result

